version: "3.8"
services:
  app:
    image: wbso/agmc-go:latest

  db:
    image: mariadb:10.9
    env_file:
      - .env
    ports:
      - 127.0.0.1:34306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata:
    external: true
    name: mysql_volume
